# Generated by Django 3.2.16 on 2023-05-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20230326_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='status',
        ),
    ]
