# Generated by Django 3.2.16 on 2023-05-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_state_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='filed',
            new_name='archive',
        ),
    ]
