# Generated by Django 3.2.16 on 2023-05-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_filed_message_archive'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Msg',
        ),
    ]
